### PR TITLE
added dashboard hosted on jsfiddle refs #9

### PR DESCRIPTION
**Pull request by gingerlime**
- using `gimel dashboard` will open the jsfiddle url
  and pass the api url, key and namespace

### CODE REVIEW

**Comment by gingerlime** [comment]
@314l5926 could you take a look at this PR / dashboard ?

**Comment by 314l5926** [comment]
Sure, I will tomorrow

**Comment by gingerlime** [comment]
Cool, thanks. Let me know if you have any questions or suggestions to improve things.

**Comment by 314l5926** [comment]
I've tested the dashboard for a couple of days, in general it is really nice. Currently, first variation is considered as an A experiment, and all other variations are compared against it. Maybe, it would be better to have a matrix, with X-vs-all win probabilities?
The other feature I missing, is Delete button for experiments, goals and variations :)

To be continued

**Comment by gingerlime** [comment]
Thanks @314l5926 ! You mention some of the things I want to improve.
- variations - I'm thinking of maybe changing Alephbet.js to indicate which variation is the control, and then set some flag in gimel. Then when we render the dashboard, we can pick the right one. Alternatively, using the UI to pick the control is also possible
- choosing experiments, deleting (or even just hiding) etc from the UI is also high on my list.
- saving any selections in localStorage, or even pushing some dashboard configs via the API.

In any case, one step at a time :)

**Pull request merged**
