### PR TITLE
delete experiment method added

### PR DESCRIPTION
**Pull request by 314l5926**
I was unable to configure API Gateway to properly create DELETE/POST method for resource, need help there

### CODE REVIEW

**Comment by gingerlime** [comment]
It was faster than I expected! Thanks. 

One thing that jumped out already is that you're using `GET` where it should be `DELETE`, but API GW is a weird creature... I'll take a look in more detail later and see if I can get this thing working... Did you get any particular error?

**Comment by gingerlime** [comment]
@314l5926 I pushed a couple of changes that should hopefully get things going. Can you test out the `delete_experiment` branch and let me know if it works for you now?

**Comment by 314l5926** [comment]
@gingerlime I've checked delete_experiment branch, everything works as expected.

**Comment by gingerlime** [comment]
Great to know, @314l5926. I'll get this ready to merge and release. Thanks again for your contribution!

**Comment by gingerlime** [comment]
merged from `delete_experiment` and bumped to `v1.1.0`

**Pull request closed without merging**
